name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ci-cd-demo.pem
          chmod 400 ~/.ssh/ci-cd-demo.pem

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > inventory
          echo "ec2-server ansible_host=${{ secrets.EC2_IP }} ansible_user=${{ secrets.EC2_NAME }} ansible_ssh_private_key_file=~/.ssh/ci-cd-demo.pem" >> inventory
          echo "cat "

      - name: Deploy application to EC2
        run: |
          ansible-playbook -i inventory ansible/deploy.yml
