name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Pytest
        run: pip install pytest

      - name: Run tests
        run: python3 -m pytest

      - name: Build Docker image
        run: docker build -t ci-cd-pipeline .

      - name: Login to the DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push Docker image
        run: docker push syamsundar721/ci-cd-pipeline:latest
